#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import sys
sys.path.append('/usr/lib/pservers')
from ps_param import PsParam
from ps_daemon import PsDaemon

param = PsParam()
obj = PsDaemon(param)
obj.run()
sys.exit(0)
